export const LOAD_ALBUMS_REQUEST = "LOAD_ALBUMS_REQUEST";
export const LOAD_ALBUMS_SUCCESS = "LOAD_ALBUMS_SUCCESS";

export const LOAD_ALBUM_REQUEST = "LOAD_ALBUM_REQUEST";
export const LOAD_ALBUM_SUCCESS = "LOAD_ALBUM_SUCCESS";

export const LOAD_TRACKS_REQUEST = "LOAD_TRACKS_REQUEST";
export const LOAD_TRACKS_SUCCESS = "LOAD_TRACKS_SUCCESS";

export const LOGIN_CLIENT_REQUEST = 'LOGIN_CLIENT_REQUEST';
export const LOGIN_CLIENT_SUCCESS = 'LOGIN_CLIENT_SUCCESS';
